version: "3.8"

services:
  postgres:
    container_name: postgres
    build: "./postgres"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  go:
    container_name: go
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "9090:9090"

volumes:
  dbdata: # persist database